### ISSUE TITLE
Weird giant black border around unfocused windows (20.10 Beta)

### ISSUE THREAD

**Issue by dylanmartinezs** [UbuntuDDE/bugs#18] opened 2020-10-05 17:01 UTC
**Describe the bug**
Whenever a non-fullscreen window loses focus, a giant black border is drawn around it.

**To Reproduce**
Log in to UbuntuDDE, and then lock the computer. Then, open two windows, the unfocused one should have a giant black border around it.

**Expected behavior**
There shouldn't be a black border.

**Screenshots**
![photo_2020-10-05_18-59-27](https://user-images.githubusercontent.com/25688218/95109626-2203b580-073d-11eb-887a-d288a8bbdbe7.jpg)

**Desktop (please complete the following information):**
 - Version [e.g. 20.10 Beta]

**Additional context**
I don't think it's needed.

**Comment by openarun** [comment] 2020-10-07 14:36
Dupe of #2

**Closed as completed by openarun** 2020-10-07 14:36 UTC
Labels: bug, groovy
