### ISSUE TITLE
System Monitor Always Shows 0.0% CPU Usage On Graph

### ISSUE THREAD

**Issue by Schykle** [UbuntuDDE/bugs#33] opened 2020-11-03 22:01 UTC
**Describe the bug**
The Deepin System Monitor seems not to display CPU usage on its graph, however memory and network metrics do seem to be reflected.

![image](https://user-images.githubusercontent.com/58709504/98045190-51155180-1de5-11eb-985a-736e88eb4812.png)

Ubuntu DDE Remix 20.10, fully updated as of writing.

**System Info**
```
System:    Kernel: 5.8.0-26-generic x86_64 bits: 64 compiler: gcc v: 10.2.0 Desktop: Deepin 20.10 
           Distro: Ubuntu 20.10 (Groovy Gorilla) 
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME B350-PLUS v: Rev X.0x serial: <filter> UEFI: American Megatrends 
           v: 5407 date: 12/31/2019 
CPU:       Info: 8-Core model: AMD Ryzen 7 2700 bits: 64 type: MT MCP arch: Zen+ rev: 2 L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 108799 
           Speed: 2436 MHz min/max: 1550/3400 MHz boost: disabled Core speeds (MHz): 1: 1378 2: 1378 3: 1377 4: 1377 
           5: 1375 6: 1384 7: 1378 8: 1372 9: 1377 10: 1377 11: 1373 12: 1774 13: 1372 14: 1375 15: 1378 16: 1377 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] 
           vendor: XFX Pine driver: amdgpu v: kernel bus ID: 0c:00.0 
           Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa 
           resolution: 3840x1080~144Hz 
           OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.38.0 5.8.0-26-generic LLVM 11.0.0) v: 4.6 Mesa 20.2.1 
           direct render: Yes 
Audio:     Device-1: Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series] driver: snd_hda_intel v: kernel 
           bus ID: 09:00.0 
           Device-2: Advanced Micro Devices [AMD/ATI] Navi 10 HDMI Audio driver: snd_hda_intel v: kernel bus ID: 0c:00.1 
           Device-3: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel 
           bus ID: 0e:00.3 
           Device-4: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo bus ID: 1-1.3:4 
           Device-5: C-Media Blue Snowball type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 3-4:2 
           Device-6: Kingston HyperX 7.1 Audio type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-9:6 
           Sound Server: ALSA v: k5.8.0-26-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK driver: r8169 v: kernel 
           port: f000 bus ID: 04:00.0 
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 6.60 TiB used: 671.85 GiB (9.9%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 960 EVO 250GB size: 232.89 GiB 
           ID-2: /dev/sda vendor: Western Digital model: WDS500G2B0A-00SM50 size: 465.76 GiB 
           ID-3: /dev/sdb vendor: Western Digital model: WDS500G2B0A-00SM50 size: 465.76 GiB 
           ID-4: /dev/sdc vendor: Western Digital model: WDS500G2B0A-00SM50 size: 465.76 GiB 
           ID-5: /dev/sdd type: USB vendor: Western Digital model: WD easystore 2624 size: 4.55 TiB 
           ID-6: /dev/sde vendor: Western Digital model: WDS500G2B0A-00SM50 size: 465.76 GiB 
Partition: ID-1: / size: 230.88 GiB used: 33.51 GiB (14.5%) fs: btrfs dev: /dev/nvme0n1p3 
           ID-2: /boot size: 975.9 MiB used: 229.0 MiB (23.5%) fs: ext4 dev: /dev/nvme0n1p2 
           ID-3: /home size: 230.88 GiB used: 33.51 GiB (14.5%) fs: btrfs dev: /dev/nvme0n1p3 
Swap:      ID-1: swap-1 type: zram size: 1024.0 MiB used: 0 KiB (0.0%) dev: /dev/zram0 
Sensors:   System Temperatures: cpu: 31.1 C mobo: N/A gpu: amdgpu temp: 49.0 C 
           Fan Speeds (RPM): N/A gpu: amdgpu fan: 0 
Info:      Processes: 434 Uptime: 21m Memory: 31.36 GiB used: 2.57 GiB (8.2%) Init: systemd runlevel: 5 Compilers: 
           gcc: 10.2.0 Packages: 1940 Shell: Bash v: 5.0.17 inxi: 3.1.07 
```

**Comment by z966768** [comment] 2020-11-20 01:43
This problem will be fundamentally fixed in the follow-up, and unnecessary changes will not be made for the time being

**Comment by Schykle** [comment] 2020-11-20 01:46
> This problem will be fundamentally fixed in the follow-up, and unnecessary changes will not be made for the time being

What is the "follow-up"?

**Comment by anantamishra** [comment] 2021-01-12 14:00
Hi there,
This issue was already fixed and the patch was sent via updates. And can't reproduce it anymore.
Feel free to reopen if it's an issue again with appropriate steps to reproduce.
Thanks!

**Closed as completed** 2021-01-12 14:34 UTC
Labels: bug, groovy
