### ISSUE TITLE
Notification Center does not appear in tray in UbuntuDDE 20.10

### ISSUE THREAD

**Issue by ddebob6** [UbuntuDDE/bugs#45] opened 2020-11-15 16:59 UTC
Although the Notification Center is shown ticked as a default tray plugin, it doesn't actually appear (or at least not on my system). You can make it appear by un-ticking and then re-ticking the entry in Plugins, but the tray icon is shown only in black and disappears again when you reboot.

**Comment by anantamishra** [comment] 2020-11-15 17:09
DUP of #20

**Comment by anantamishra** [comment] 2020-11-15 17:10
Duplicate of #20

**Closed as completed** 2020-11-15 17:24 UTC
