### ISSUE TITLE
DDE crashing after changing system theme

### ISSUE THREAD

**Issue by matheucomth** [UbuntuDDE/bugs#119] opened 2023-01-29 20:12 UTC
After changing the light theme to the dark theme, the DDE interface stops responding constantly, even restarting the system the problem persists, but the interface does not start, only the error popup.

**Comment by openarun** [comment] 2023-01-29 21:36
dupe of #113 .
A fix has been already released.

**Closed as completed** 2023-01-30 09:55 UTC
Labels: jammy
