### ISSUE TITLE
Update request for several outdated applications and corrections made

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#64] opened 2020-11-30 11:18 UTC
Hello Ubuntu-DDE 20.10 Team

Request to update Nomacs from 3.12 to 3.16, Evolution 3.81 to 3.82, CMake 3.16.3 to 3.19. Synaptic from 0.84 to 0.90.2, Kodi 18.8 to 18.9, if possible in Brazilian Portuguese and other languages?

Please (!)

Note: The Deepin V20 1003 distro has all applications and Distro in Brazilian Portuguese. Why does Ubuntu-DDE 20.10 remain in Portuguese in Portugal and English?

@openarun

**Comment by openarun** [comment] 2020-12-03 15:52
Hello @serial02,
We see your request but we extremely rely on the Ubuntu repository for the above-listed software. Please have patience and when the packages are available in Ubuntu repository, it will be available for updates to UbuntuDDE Remix too.
For now, I am not closing this bug report, you can close it when your issue with the above package updates are solved.
Thanks for your bug report!

**Comment by openarun** [comment] 2020-12-03 15:54
Regarding your request with the language support, you have already filed a bug report against it.
So, dupe of #42

**Comment by openarun** [comment] 2020-12-03 16:01
Same goes to #50

**Comment by serial02** [comment] 2020-12-03 16:10
> Regarding your request with the language support, you have already filed a bug report against it.
> So, dupe of #42

Hello @openarun 

Exactly, but here I am emphasizing the updates of the most recent applications, as they received numerous corrections, see reports on the pages of the corresponding applications.

Thanks for the feedback

**Comment by openarun** [comment] 2021-02-08 07:21
We rely on the Ubuntu repository for the above packages. And as Ubuntu doesn't have a rolling release scheme for releases, if you need the latest version, please try getting the package from the upstream.

**Closed as completed by openarun** 2021-02-08 07:21 UTC
