### ISSUE TITLE
When selecting the control center options, the taskbar icons disappear

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#55] opened 2020-11-25 02:13 UTC
Hello Ubuntu-DDE Team 20.10

When selecting the options of the control center, the icons on the taskbar disappear and return, flash and configure the image of the icons.

More details can be seen in this gif image below:

![Screen Capture_select-area_20201124230206](https://user-images.githubusercontent.com/32621790/100173748-e0c09400-2ea9-11eb-8fd5-18559de8d1b2.gif)

Maybe this can help: Journalctl -xe Ubuntu-DDE 24/11/2020 as 22:00h ( https://pastebin.com/xk5bXfU5 )

```
OS: Ubuntu 20.10 x86_64  
Kernel: 5.8.0-29-generic 
Uptime: 3 hours, 36 mins 
Packages: 2231 (dpkg) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: Deepin 20.10 
WM: KWin 
Icons: bloom [GTK2/3] 
Terminal: deepin-terminal 
CPU: Intel i3 540 (4) @ 3.067GHz 
GPU: Intel Core Processor 
Memory: 3403MiB / 7694MiB 
```

**Comment by ddebob6** [comment] 2020-11-25 12:25
Not as yet been able to duplicate this, but then I am currently using Nouveau. Possible driver issue?

**Comment by serial02** [comment] 2020-11-30 22:35
> Not as yet been able to duplicate this, but then I am currently using Nouveau. Possible driver issue?

Hello

I do not think so.

Adding: In the personalization control center, the settings are changed when clicking on the tabs and, when restarting, the font options are empty. I think the problem is in the control center.

![Screen Capture_select-area_20201130181755](https://user-images.githubusercontent.com/32621790/100673805-de938500-3342-11eb-91fe-09439f2dd980.gif)

**Comment by anantamishra** [comment] 2021-01-24 08:22
Hello @serial02 , we are not able to reproduce it anymore, can you please update the system with the latest updates from the UbuntuDDE Team and give the feedback on that.

**Comment by openarun** [comment] 2021-01-25 16:50
I'm closing this bug report as I'm unable to reproduce, feel free to reopen if it still persist after the latest update.

**Closed as completed by openarun** 2021-01-25 16:50 UTC
Labels: bug
